# ================================================
# app.yaml - Google Cloud App Engine Configuration
# ================================================

runtime: python312

# Basic scaling for always-on bot
instance_class: F1

# Environment variables
env_variables:
  PYTHON_VERSION: "3.12"

# Handlers
handlers:
- url: /.*
  script: auto
  secure: always

# Entrypoint
entrypoint: python app.py

# Automatic restart on failure
automatic_scaling:
  min_instances: 1
  max_instances: 1













